from __future__ import annotations

import json
import tomllib
from pathlib import Path
from typing import Any

from .exceptions import InvalidInputError
from .models import ProjectConfig, WorkflowProfile
from .models.io import atomic_write_text, parse_contract_body
from .security import ensure_within_allowed_roots

CONFIG_NAME = "photonic.toml"


def find_project_root(start: Path | None = None) -> Path:
    current = (start or Path.cwd()).resolve()
    if current.is_file():
        current = current.parent
    for candidate in (current, *current.parents):
        if (candidate / CONFIG_NAME).is_file():
            return candidate
    raise InvalidInputError(f"no {CONFIG_NAME} found at or above {current}")


def load_project_config(project_root: Path | None = None) -> tuple[Path, ProjectConfig]:
    root = find_project_root(project_root) if project_root is None else project_root.resolve()
    path = root / CONFIG_NAME
    try:
        with path.open("rb") as handle:
            payload = tomllib.load(handle)
    except FileNotFoundError as exc:
        raise InvalidInputError(f"project configuration not found: {path}") from exc
    except tomllib.TOMLDecodeError as exc:
        raise InvalidInputError(f"invalid TOML in {path}: {exc}") from exc
    try:
        config = parse_contract_body(payload, "ProjectConfig")
    except InvalidInputError as exc:
        raise InvalidInputError(f"invalid project configuration {path}: {exc}") from exc
    assert isinstance(config, ProjectConfig)
    return root, config


def _toml_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, list):
        return "[" + ", ".join(_toml_value(item) for item in value) + "]"
    if isinstance(value, dict):
        return "{ " + ", ".join(
            f"{json.dumps(str(key))} = {_toml_value(item)}" for key, item in sorted(value.items())
        ) + " }"
    raise TypeError(f"unsupported TOML value type: {type(value).__name__}")


def project_config_toml(config: ProjectConfig) -> str:
    payload = config.model_dump(mode="json", exclude_none=True)
    preferred_order = (
        "schema_version",
        "stable_id",
        "name",
        "revision",
        "source",
        "created_at",
        "provenance",
        "status",
        "validity",
        "profile",
        "workspace",
        "pdk_alias",
        "adapter_defaults",
        "adapter_entrypoint_allowlist",
        "allowed_roots",
        "dry_run",
        "timeout_s",
        "commercial_concurrency",
        "commercial_parallel_authorized",
        "matlab_executable_alias",
        "matlab_execution_model",
        "matlab_toolbox_path_aliases",
        "matlab_product_requirements",
        "comsol_livelink",
        "lumerical_api_alias",
        "instrument_aliases",
        "redaction",
        "artifact_limit_mb",
        "packaging_profile",
        "test_profile",
    )
    lines = [
        "# Generated by photonic init. Physical design inputs are intentionally not inherited here.",
    ]
    remaining = sorted(set(payload) - set(preferred_order))
    for key in (*preferred_order, *remaining):
        if key in payload:
            lines.append(f"{key} = {_toml_value(payload[key])}")
    return "\n".join(lines) + "\n"


def make_project_config(
    root: Path,
    *,
    profile: WorkflowProfile,
    name: str | None = None,
) -> ProjectConfig:
    stable_id = "".join(character if character.isalnum() or character in "._:-" else "-" for character in root.name)
    stable_id = stable_id.strip("-") or "photonic-project"
    return ProjectConfig(
        stable_id=stable_id,
        name=name or root.name,
        source="photonic init",
        status="active",
        validity="valid",
        profile=profile,
        workspace=".",
        allowed_roots=["."],
    )


def write_project_config(root: Path, config: ProjectConfig, *, overwrite: bool = False) -> Path:
    path = root / CONFIG_NAME
    if path.exists() and not overwrite:
        raise InvalidInputError(f"project configuration already exists: {path}")
    atomic_write_text(path, project_config_toml(config))
    return path


def resolved_allowed_roots(root: Path, config: ProjectConfig) -> list[Path]:
    roots: list[Path] = []
    for raw in config.allowed_roots:
        candidate = Path(raw)
        roots.append((root / candidate).resolve() if not candidate.is_absolute() else candidate.resolve())
    if not roots:
        roots.append(root.resolve())
    ensure_within_allowed_roots(root, roots)
    return roots
